//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMarket.WindowsService.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class FilterValue
    {
        public int FilterValueId { get; set; }
        public int FilterId { get; set; }
        public string FilterValueName { get; set; }
        public string DisplayName { get; set; }
        public System.DateTime AddedDate { get; set; }
        public string AddedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<byte> Value { get; set; }
    
        public virtual Filter Filter { get; set; }
    }
}
