//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMarket.WindowsService.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SavedFilter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SavedFilter()
        {
            this.SavedIds = new HashSet<SavedId>();
        }
    
        public int SavedFilterId { get; set; }
        public string ListName { get; set; }
        public string Query { get; set; }
        public int Count { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int UserId { get; set; }
        public Nullable<int> StatusId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SavedId> SavedIds { get; set; }
        public virtual Status Status { get; set; }
        public virtual User User { get; set; }
    }
}
