//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMarket.WindowsService.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SavedId
    {
        public int SavedId1 { get; set; }
        public int FilterValueId { get; set; }
        public int FilterId { get; set; }
        public int GroupId { get; set; }
        public int SavedFilterId { get; set; }
        public Nullable<int> Count { get; set; }
    
        public virtual SavedFilter SavedFilter { get; set; }
    }
}
